### ISSUE TITLE
Windows 11 Support

### ISSUE THREAD

**Issue by rgaudin** [offspot/captive-portal#2]
- [x] Android 12
- [x] Windows 11
- [x] macOS Monterrey
- [x] iOS 15.1

**Comment by rgaudin** [comment]
Tested on all systems. Works as previously except for Windows 11 where the hotspot works but there is no captive portal displayed.  I am thus converting this into a bug as we want the captive portal to trigger everywhere.

**Comment by kelson42** [comment]
@rgaudin Might be good to fix that considering that Win11 has already 25% of market share https://www.thurrott.com/windows/269495/windows-11-market-share-adduplex-june-2022

**Comment by rgaudin** [comment]
I am unable to access a W11 machine and the PCs I have at end are not compatible… and it's not possible to bypass CPU restriction anymore AFAIK

**Comment by rgaudin** [comment]
It's actually a Windows bug as described [here](https://airangel.com/airangel-blog/windows-11-captive-portals/) and referencing an upstream ticket: Windows 11 doesn't start the browser automatically so User would have to attempt a web visit to see the captive UI (or use Firefox).

It seems to have been fixed in a update, as I could confirm so I am closing this as completed.

For the record, I had network issues during my tests because I am testing with an USB WiFi card over a virtualbox installation for which network was disabled. I also had similar difficulties connecting to a *regular* WiFi network but I'm leaving this comment for future me that gets a chance to test on an actual W11 box.
